version: "3"

services:

  database-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo_database
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongoDB:/data/db
